import type { Load, KPIData, Driver, Broker, Invoice } from '@/types'

export const kpiData: KPIData = {
  activeLoads: 12,
  avgAIScore: 8.2,
  revenueToday: 45800,
  pendingInvoices: 8,
  whatsappMessages: 34,
}

export const loads: Load[] = [
  {
    id: '1',
    loadNumber: 'LD-2401',
    broker: 'TQL Logistics',
    pickup: 'Atlanta, GA',
    delivery: 'Miami, FL',
    rate: 2400,
    rpm: 3.64,
    aiScore: 9.1,
    status: 'available',
    driver: null,
  },
  {
    id: '2',
    loadNumber: 'LD-2402',
    broker: 'C.H. Robinson',
    pickup: 'Chicago, IL',
    delivery: 'Dallas, TX',
    rate: 3200,
    rpm: 3.46,
    aiScore: 8.5,
    status: 'assigned',
    driver: 'John Smith',
  },
  {
    id: '3',
    loadNumber: 'LD-2403',
    broker: 'Landstar',
    pickup: 'Los Angeles, CA',
    delivery: 'Phoenix, AZ',
    rate: 1800,
    rpm: 4.83,
    aiScore: 9.3,
    status: 'in_transit',
    driver: 'Mike Johnson',
  },
  {
    id: '4',
    loadNumber: 'LD-2404',
    broker: 'XPO Logistics',
    pickup: 'New York, NY',
    delivery: 'Boston, MA',
    rate: 850,
    rpm: 3.95,
    aiScore: 7.8,
    status: 'available',
    driver: null,
  },
  {
    id: '5',
    loadNumber: 'LD-2405',
    broker: 'J.B. Hunt',
    pickup: 'Houston, TX',
    delivery: 'Memphis, TN',
    rate: 2200,
    rpm: 3.89,
    aiScore: 8.2,
    status: 'delivered',
    driver: 'Sarah Williams',
  },
]

export const drivers: Driver[] = [
  {
    id: '1',
    name: 'John Smith',
    phone: '(555) 123-4567',
    status: 'on_load',
    location: 'Dallas, TX',
    totalLoads: 142,
    totalRevenue: 284000,
  },
  {
    id: '2',
    name: 'Mike Johnson',
    phone: '(555) 234-5678',
    status: 'on_load',
    location: 'Phoenix, AZ',
    totalLoads: 98,
    totalRevenue: 196000,
  },
  {
    id: '3',
    name: 'Sarah Williams',
    phone: '(555) 345-6789',
    status: 'available',
    location: 'Memphis, TN',
    totalLoads: 156,
    totalRevenue: 312000,
  },
]

export const brokers: Broker[] = [
  {
    id: '1',
    companyName: 'TQL Logistics',
    contactName: 'Robert Johnson',
    phone: '(513) 555-0123',
    email: 'dispatch@tql.com',
    paymentReliability: 98,
    totalLoads: 145,
    totalRevenue: 362500,
  },
  {
    id: '2',
    companyName: 'C.H. Robinson',
    contactName: 'Jennifer Smith',
    phone: '(952) 555-0456',
    email: 'carriers@chrobinson.com',
    paymentReliability: 95,
    totalLoads: 98,
    totalRevenue: 245000,
  },
  {
    id: '3',
    companyName: 'Landstar',
    contactName: 'Michael Davis',
    phone: '(904) 555-0789',
    email: 'capacity@landstar.com',
    paymentReliability: 92,
    totalLoads: 76,
    totalRevenue: 190000,
  },
]

export const invoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    loadNumber: 'LD-2401',
    broker: 'TQL Logistics',
    amount: 2400,
    status: 'sent',
    dueDate: '2024-03-15',
    createdAt: '2024-02-15',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    loadNumber: 'LD-2402',
    broker: 'C.H. Robinson',
    amount: 3200,
    status: 'paid',
    dueDate: '2024-03-10',
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    loadNumber: 'LD-2403',
    broker: 'Landstar',
    amount: 1800,
    status: 'overdue',
    dueDate: '2024-02-28',
    createdAt: '2024-02-01',
  },
]
